// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjzxlornmdzbmegjfwyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqenhsb3JubWR6Ym1lZ2pmd3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDQwNDgsImV4cCI6MjA2NDkyMDA0OH0.U92oSCCchPIgYdX9buCBmOrIHSWuzXUa7eXSFiznDpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
